services:
  backendexternal:
    container_name: backendExternal
    build:
      context: ./backendExternal
    ports:
      - "5001:5001"
    volumes:
      - ./backendExternal:/app
    networks:
      - intranet
  backenduser:
    container_name: backendUser
    build:
      context: ./backendUser
    ports:
      - "5002:5002"
    volumes:
      - ./backendUser:/app
    networks:
      - intranet

networks:
  intranet:
    driver: bridge